name: stagexl_particle
version: 0.3.5+1
author: Bernhard Pichler <support@stagexl.org>
description: The particle emitter runtime for the StageXL library.
homepage: http://www.stagexl.org
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  browser: any
  stagexl: '>=0.11.0 <0.12.0'
