name: stagexl_particle
version: 0.4.0-dev
author: Bernhard Pichler <support@stagexl.org>
description: The particle emitter runtime for the StageXL library.
homepage: http://www.stagexl.org

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  stagexl: ^1.4.0

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0+4
