name: stagexl_particle
version: 0.1.0
author: Bernhard Pichler <support@stagexl.org>
description: The particle emitter runtime for the StageXL library.
homepage: http://www.stagexl.org
dependencies:
  browser: any
  stagexl: any
