name: stagexl_particle
version: 0.3.4
author: Bernhard Pichler <support@stagexl.org>
description: The particle emitter runtime for the StageXL library.
homepage: http://www.stagexl.org
environment:
  sdk: '>=0.1.6 <2.0.0'
dependencies:
  browser: any
  stagexl: '>=0.10.2 <0.11.0'
