name: stagexl_particle_confetti
version: 1.1.0
description: Confetti Example
homepage: http://www.stagexl.org

environment:
  sdk: ^3.0.0

dependencies:
  stagexl: ^2.0.0
  stagexl_particle:
    path: ../../../stagexl_particle

dev_dependencies:
  pedantic: any
  build_runner: any
  build_test: any
  build_web_compilers: any
